name: Train and Test MNIST & Sentiment Analysis Models

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      mlflow_changed: ${{ steps.filter.outputs.mlflow }}
      metaflow_changed: ${{ steps.filter.outputs.metaflow }}
      mlflow_sentiment_changed: ${{ steps.filter.outputs.mlflow_sentiment }}
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Filtrar archivos modificados
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            mlflow:
              - 'MLflow/mlflowMain.py'
              - 'MLflow/mlflowTest.py'
            metaflow:
              - 'metaflowMain.py'
            mlflow_sentiment:
              - 'MLflow/mlflowMain_sentiment.py'
              - 'MLflow/mlflowTest_sentiment.py'

  MLflow_job:
    needs: check-files
    if: needs.check-files.outputs.mlflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r MLflow/requirements.txt

      - name: Entrenar modelo con MLflow
        run: python MLflow/mlflowMain.py      

      - name: Subir artifacts al servidor con rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 167.99.84.228 >> ~/.ssh/known_hosts

          rsync -avz /tmp/mlflow/artifacts/ root@167.99.84.228:/tmp/mlflow/artifacts

      - name: Evaluar modelo con MLflow
        run: python MLflow/mlflowTest.py
  
  MLflow_sentiment_job:
    needs: check-files
    if: needs.check-files.outputs.mlflow_sentiment_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r MLflow/requirements.txt

      - name: Entrenar Sentiment
        run: python MLflow/mlflowMain_sentiment.py

      - name: Subir artifacts al servidor con rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 167.99.84.228 >> ~/.ssh/known_hosts

          rsync -avz /tmp/mlflow/artifacts/ root@167.99.84.228:/tmp/mlflow/artifacts

      - name: Evaluar Sentiment
        run: python MLflow/mlflowTest_sentiment.py

  Metaflow_job:
    needs: check-files
    if: needs.check-files.outputs.metaflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar modelo con Metaflow
        run: |
          python metaflowMain.py
          python metaflowMain.py run

      - name: Guardar modelo 
        uses: actions/upload-artifact@v4
        with:
          name: mnist-model-metaflow
          path: modelo_entrenado_metaflow.pkl
