name: Train and Test MNIST with MLflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      mlflow_changed: ${{ steps.filter.outputs.mlflow }}
      metaflow_changed: ${{ steps.filter.outputs.metaflow }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Filtrar archivos modificados
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            mlflow:
              - 'mlflowMain.py'
              - 'mlflowTest.py'
            metaflow:
              - 'metaflowMain.py'

  MLflow_job:
    needs: check-files
    if: needs.check-files.outputs.mlflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Establecer variable de entorno MLFLOW_ARTIFACT_URI
        run: |
          echo "MLFLOW_ARTIFACT_URI=file:/tmp/mlflow_artifacts" >> $GITHUB_ENV

      - name: Entrenar modelo con MLflow
        run: python mlflowMain.py      

      - name: Evaluar modelo con MLflow
        run: python mlflowTest.py

  Metaflow_job:
    needs: check-files
    if: needs.check-files.outputs.metaflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar modelo con Metaflow
        run: |
          python metaflowMain.py
          python metaflowMain.py run

      - name: Guardar modelo 
        uses: actions/upload-artifact@v4
        with:
          name: mnist-model-metaflow
          path: modelo_entrenado_metaflow.pkl
