name: Train and Test MNIST with MLflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  train_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Entrenar modelo con MLflow
        run: python mlflowMain.py      

      - name: Guardar modelo (solo si se entrena correctamente)
        uses: actions/upload-artifact@v4
        with:
          name: mnist-model
          path: modelo_entrenado.pkl
      
      - name: Descargar el modelo entrenado
        uses: actions/download-artifact@v4
        with:
          name: mnist-model

      - name: Evaluar modelo con MLflow
        run: python mlflowTest.py

