name: Train and Test MNIST with MLflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      mlflow_changed: ${{ steps.filter.outputs.mlflow }}
      metaflow_changed: ${{ steps.filter.outputs.metaflow }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Filtrar archivos modificados
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            mlflow:
              - 'mlflowMain.py'
              - 'mlflowTest.py'
            metaflow:
              - 'metaflowMain.py'

  MLflow_job:
    needs: check-files
    if: needs.check-files.outputs.mlflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create temporary directories with proper permissions
        run: |
          mkdir -p /tmp/mlflow-data
          chmod 777 /tmp/mlflow-data
          echo "Created temporary directory with full permissions"

      - name: Entrenar modelo con MLflow
        env:
          MLFLOW_TRACKING_URI: "http://167.99.84.228:5000"
          MLFLOW_TRACKING_DIR: "/tmp/mlflow-data/tracking"
          MLFLOW_ARTIFACTS_DESTINATION: "/tmp/mlflow-data/artifacts"
          MLFLOW_ROOT_ARTIFACT_URI: "/tmp/mlflow-data/root-artifacts"
          MLFLOW_ARTIFACT_ROOT: "/tmp/mlflow-data/artifacts-root" 
          MLFLOW_RUN_ARTIFACT_ROOT: "/tmp/mlflow-data/run-artifacts"
          MLFLOW_REGISTRY_URI: "/tmp/mlflow-data/registry"
          TMPDIR: "/tmp/mlflow-data"
        run: python mlflowMain.py      

      - name: Evaluar modelo con MLflow
        run: python mlflowTest.py

  Metaflow_job:
    needs: check-files
    if: needs.check-files.outputs.metaflow_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar modelo con Metaflow
        run: |
          python metaflowMain.py
          python metaflowMain.py run

      - name: Guardar modelo 
        uses: actions/upload-artifact@v4
        with:
          name: mnist-model-metaflow
          path: modelo_entrenado_metaflow.pkl
